name: Upload Python Package

on:
  workflow_dispatch:

permissions:
  contents: write
  discussions: write

jobs:
  deploy:
    env:
      binary_name: devcontainer-contrib

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        python -m pip install --upgrade build setuptools wheel  setuptools-scm

    - name: Build package
      run: python -m build --wheel

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true

    - name: run pyoxidizer
      id: run_pyoxidizer

      run: |
        python -m pip install --upgrade pip 
        python -m pip install pyoxidizer

        oxidizer_location=$GITHUB_WORKSPACE/pyoxidizer-devcontainer-contrib
        wheel_location=./dist/$(ls dist | grep .whl)
        target_triple="x86_64-unknown-linux-gnu"
        run_command="from devcontainer_contrib.__main__ import main; main()"
        python_version="3.10"


        pyoxidizer build exe \
          --path $oxidizer_location \
          --release \
          --var wheel_location $wheel_location \
          --var run_command "$run_command" \
          --var python_version $python_version \
          --var app_name $binary_name \
          --target-triple $target_triple 

        mv "$oxidizer_location/build/$target_triple/release/exe/$binary_name" $GITHUB_WORKSPACE/$binary_name

        echo "binary_location=$GITHUB_WORKSPACE/$binary_name" >> "$GITHUB_OUTPUT"

    - name: Run UPX
      uses: crazy-max/ghaction-upx@v2
      with:
        version: "v4.0.2"
        files: |
          ${{ steps.run_pyoxidizer.outputs.binary_location }}

        args: -1

    - name: create checksum
      id: create_checksum

      run: |
        sha256sum ${{ steps.run_pyoxidizer.outputs.binary_location }} > $GITHUB_WORKSPACE/checksums.txt
        sha256sum -c $GITHUB_WORKSPACE/checksums.txt
        echo "checksum_location=$GITHUB_WORKSPACE/checksums.txt" >> "$GITHUB_OUTPUT"


    - name: GH Release
      uses: softprops/action-gh-release@v0.1.15
      with:
          files: |
            ${{ steps.run_pyoxidizer.outputs.binary_location }}
            ${{ steps.create_checksum.outputs.checksum_location }}

    # - name: Publish package
    #   uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
    #   with:
    #     user: __token__
    #     password: ${{ secrets.PYPI_API_TOKEN }}